services:
  - type: web
    name: hymes-web
    runtime: node
    plan: free
    region: frankfurt # proche de Supabase eu-west-3 (Paris)
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.19.4
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_TOKEN
        sync: false
